theme: jekyll-theme-minimal
title: LatLong.Net SDK .NET SDK
description: A repository template for .NET API client projects
logo: https://raw.githubusercontent.com/guibranco/LatLongNet-SDK-dotnet/main/logo.png
show_downloads: true
